monitor/app/models/ban.py
# -*- coding:utf-8 -*-

from monitor.app.ext.database import db


class Ban(db.Model):
    __tablename__ = 'bans'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    # 域名
    netloc = db.Column(db.String, nullable=False, unique=True)
    only_netloc = db.Column(db.Boolean, default=True)
    path = db.relation("Path",
                       backref='ban',
                       order_by="Path.full_path",
                       lazy='dynamic', cascade="all, delete")

    def __init__(self, netloc, only_netloc):
        self.netloc = netloc
        self.only_netloc = only_netloc


class Path(db.Model):
    __tablename__ = 'paths'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    ban_id = db.Column(db.Integer, db.ForeignKey('bans.id'))
    full_path = db.Column(db.String, nullable=False)

    def __init__(self, full_path):
        self.full_path = full_path

monitor/app/forms/ban.py
# -*- coding:utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, BooleanField, HiddenField
from wtforms.validators import URL, DataRequired


class FlowBanForm(FlaskForm):
    url = StringField(u'URL',
                      validators=[URL(message=u"错误的网址"), DataRequired()])
    only_netloc = BooleanField(u'仅屏蔽域名', default=True)
    netloc = HiddenField(u'netloc', validators=[DataRequired()])
    full_path = HiddenField(u'full_path', validators=[DataRequired()])
    submit = SubmitField(u'提交')


class BanForm(FlaskForm):
    url = StringField(u'URL', validators=[URL(), DataRequired()])
    only_netloc = BooleanField(u'仅屏蔽域名', default=True)
    submit = SubmitField(u'添加')

monitor/app/views/ban.py
# -*- coding:utf-8 -*-

from flask import (Blueprint, render_template, request, abort, flash, redirect,
                   url_for)
from flask_login import login_required

from mitmproxy.net.http.url import parse
from monitor.app import db
from monitor.app.forms.ban import BanForm
from monitor.app.models import Ban, Path

ban = Blueprint('ban', 'monitor')


@ban.route('/', methods=['GET', 'POST'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Ban.query().paginate(page, per_page=30, error_out=False)
    bans = pagination.items

    form = BanForm()
    if form.validate_on_submit():
        # parse 返回的是bytes类型
        scheme, netloc, port, full_path = parse(form.url.data.strip())
        scheme = scheme.decode('utf-8')
        netloc = netloc.decode('utf-8')
        full_path = full_path.decode('utf-8')
        ban = Ban.query(netloc=netloc).first()
        if not ban:
            newban = Ban(netloc=netloc, only_netloc=form.only_netloc.data)
            if not form.only_netloc.data:
                path = Path(full_path=full_path)
                newban.path.append(path)
            db.session.add(newban)
            db.session.commit()
        else:
            ban.only_netloc = form.only_netloc.data
            if not form.only_netloc.data:
                path = Path(full_path=full_path)
                ban.path.append(path)
            db.session.add(ban)
            db.session.commit()
        flash(u'添加成功')
        return redirect(url_for('ban.index'))
    return render_template('ban/index.jinja', bans=bans,
                           pagination=pagination, form=form)


@ban.route('/<int:ban_id>', methods=['GET'])
@login_required
def detail(ban_id):
    b = Ban.get(ban_id)
    if not b:
        abort(404)
    if not b.path.first():
        redirect(url_for('ban.index'))
    return render_template('ban/detail.jinja', ban=b)


@ban.route('/<int:ban_id>/<int:path_id>', methods=['GET'])
@login_required
def delete_path(ban_id, path_id):
    path = Path.get(path_id)
    if not path:
        abort(404)
    db.session.delete(path)
    b = Ban.get(ban_id)
    if b and not b.path.first():
        b.only_netloc = True
        db.session.add(b)
        db.session.commit()
        return redirect(url_for('ban.index'))
    return redirect(url_for('ban.detail', ban_id=ban_id))


@ban.route('/<int:ban_id>/delete', methods=['GET'])
def delete_ban(ban_id):
    b = Ban.get(ban_id)
    if not b:
        abort(404)
    db.session.delete(b)
    db.session.commit()
    return redirect(url_for('ban.index'))

monitor/app/templates/ban/detail.jinja
{% extends 'base.jinja' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
    <div class="container">
        <div class="row">
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>网址</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for path in ban.path %}
                    <tr>
                        <td>{{ path.id }}</td>
                        <td>
                            <a href="{{ '//' + ban.netloc + path.full_path }}"
                               target="_blank"
                               title="{{ path.full_path }}">{{ path.full_path | truncate(99) }}</a>
                        </td>
                        <td>
                            <a href="{{ url_for('ban.delete_path', ban_id=ban.id, path_id=path.id) }}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if pagination %}
            <div class="row text-center">
                {{ macros.pagination_widget(pagination, 'ban.detail') }}
            </div>
        {% endif %}
    </div>
{% endblock %}

monitor/app/templates/ban/index.jinja
{% extends 'base.jinja' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import '_macros.jinja' as macros %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>编号</th>
                        <th>域名</th>
                        <th>仅屏蔽域名</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ban in bans %}
                        <tr>
                            <td>{{ ban.id }}</td>
                            <td>
                                <a href="{{ "//" ~ ban.netloc }}"
                                   target="_blank">{{ ban.netloc }}</a>
                            </td>
                            {% if ban.only_netloc %}
                                <td><b>是</b></td>
                                <td>
                                </td>
                            {% else %}
                                <td><b>否</b></td>
                                <td>
                                    <a href="{{ url_for('ban.detail', ban_id=ban.id) }}">查看</a>
                                </td>
                            {% endif %}
                            <td>
                                <a href="{{ url_for('ban.delete_ban', ban_id=ban.id) }}">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if pagination %}
                    <div class="row text-center">
                        {{ macros.pagination_widget(pagination, 'ban.index') }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    <h1>新增网址</h1>
                </div>
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}