monitor/app/views/auth.py
# -*- coding:utf-8 -*-

from flask import Blueprint, flash, redirect, url_for, request, render_template
from flask_login import login_user, login_required, logout_user, current_user

from monitor.app import db
from monitor.app.forms.change import ChangePasswordForm
from monitor.app.forms.login import LoginForm
from monitor.app.forms.register import RegistrationForm
from monitor.app.models import User

auth = Blueprint('auth', 'monitor')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    exist_user = User.exists()
    if form.validate_on_submit():
        user = User.query(username=form.username.data).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user)
            flash(u'登录成功')
            return redirect(request.args.get('next') or url_for('index'))
        flash(u'错误的用户名或密码', 'error')
    return render_template('auth/login.jinja', form=form,
                           exist_user=exist_user)


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash(u'已注销登录')
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    exist_user = User.exists()
    if exist_user:
        return redirect(url_for('auth.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(u'注册成功')
        return redirect(url_for('index'))
    return render_template('auth/register.jinja', form=form)


@auth.route('/changepassword', methods=['GET', 'POST'])
@login_required
def changepassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        db.session.add(current_user)
        db.session.commit()
        logout_user()
        flash(u'修改成功，请重新登录')
        return redirect(url_for('auth.login'))
    return render_template('auth/changepassword.jinja', form=form)

monitor/app/views/errors.py
# -*- coding:utf-8 -*-

from flask import render_template
from werkzeug.exceptions import (
    HTTPException, InternalServerError, RequestTimeout,
)


def register(app):
    """ 在传输过来的app中添加错误句柄 """

    @app.errorhandler(400)
    @app.errorhandler(404)
    @app.errorhandler(500)
    def handle_error(e):
        if not isinstance(e, HTTPException):
            e = InternalServerError()

        return render_template(
            'error.jinja',
            code=e.code,
            name=e.name,
            description=e.description,
        ), e.code

    @app.errorhandler(EOFError)
    def handle_eof_error(e):
        return handle_error(RequestTimeout())

monitor/app/views/flow.py
# -*- coding:utf-8 -*-

from flask import (Blueprint, abort, flash, redirect, render_template, url_for)
from flask_login import login_required

from monitor.app import db
from monitor.app.forms.ban import FlowBanForm
from monitor.app.models import Flow, Ban
from monitor.app.models import Path

flow = Blueprint('flow', 'monitor')


@flow.route('/<int:flow_id>', methods=['GET', 'POST'])
@login_required
def detail(flow_id):
    f = Flow.get(flow_id)
    form = FlowBanForm()
    if not f:
        abort(404)
    form.url.data = f.url
    form.netloc.data = f.netloc
    form.full_path.data = f.full_path
    if form.validate_on_submit():
        ban = Ban.query(netloc=form.netloc.data).first()
        if not ban:
            newban = Ban(netloc=form.netloc.data,
                         only_netloc=form.only_netloc.data)
            if not form.only_netloc.data:
                path = Path(full_path=form.full_path.data)
                newban.path.append(path)
            db.session.add(newban)
            db.session.commit()
        else:
            ban.only_netloc = form.only_netloc.data
            if not form.only_netloc.data:
                path = Path(full_path=form.full_path.data)
                ban.path.append(path)
            db.session.add(ban)
            db.session.commit()
        flash(u'添加成功')
        return redirect(url_for('index'))
    return render_template('flow/detail.jinja', form=form)

monitor/app/templates/_macros.jinja
{% macro pagination_widget(pagination, endpoint, fragment='') %}
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="
                    {% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="
                                {{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="
                                {{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li{% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="
                    {% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}

monitor/app/templates/base.jinja
{% extends "bootstrap/base.html" %}

{% block head -%}
    {{ super() }}
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon">
{%- endblock %}

{% block navbar -%}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#monitor-navbar-collapse"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                   href="{{ url_for('index') }}">Monitor</a>
            </div>

            <div class="collapse navbar-collapse" id="monitor-navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('index') }}">首页</a></li>
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('ban.index') }}">禁止列表</a></li>
                    {% endif %}
                    <li><a href="//mitm.it/">下载证书</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            {{ current_user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">

                            <li><a href="{{ url_for('auth.changepassword') }}">修改密码</a>
                            </li>
                            <li><a href="{{ url_for('auth.logout') }}">注销</a>
                            </li>

                        </ul>
                    {% endif %}
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{%- endblock %}

{% block content -%}
    {% block message %}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close"
                        data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endblock %}
    {% block main %}
    {% endblock %}
{%- endblock content %}

{% block stripts -%}
    {{ super() }}
{%- endblock %}

monitor/app/templates/error.jinja
<!doctype html>
<html>
<head>
    <title>{{ code }} {{ name }}</title>
</head>
<body>
<h1>{{ name }}</h1>
{% if description %}<p>{{ description }}</p>{% endif %}
</body>
</html>

monitor/app/templates/index.jinja
{% extends 'base.jinja' %}
{% import '_macros.jinja' as macros %}


{% block title %}
    首页
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th>网址</th>
                    <th>访问次数</th>
                    <th>最后访问时间</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for flow in flows %}
                    <tr>
                        <td>
                            <a href="{{ "//%s%s" | format(flow.netloc, flow.full_path) }}"
                               target="_blank"
                               title="{{ "//%s%s" | format(flow.netloc, flow.full_path) }}">
                                {{ "%s://%s%s" | format(flow.scheme, flow.netloc, flow.full_path) | truncate(99) }}
                            </a>
                        </td>
                        <td>
                            {{ flow.total }}
                        </td>
                        <td>{{ flow.create_timestamp }}</td>
                        <td>
                            <a href="{{ url_for('flow.detail', flow_id=flow.id) }}">操作</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if pagination %}
            <div class="row text-center">
                {{ macros.pagination_widget(pagination, '.index') }}
            </div>
        {% endif %}
    </div>
{% endblock %}